### ISSUE TITLE
[Feature] Connect to a database

### ISSUE THREAD

**Issue by aghogwarts** [Manipal-OSF/bot#10]
**Is your feature request related to a problem? Please describe.**
Locally storing as cache wouldn't be efficient.

**Describe the solution you'd like**
Connecting the bot to a database hosted online where we could store all the activities or changes in the server and could log them. Another usecase of a database is for the member verification system.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by dhzdhd** [comment]
I believe this can be closed now as the bot now relies on the database API. @abhigyantrips
