### ISSUE TITLE
[Feature] Authentication for OSF recruits

### ISSUE THREAD

**Issue by aghogwarts** [Manipal-OSF/bot#8]
**Is your feature request related to a problem? Please describe.**
Not a problem right now but a feature we could implement in order to avoid problems like impersonation.

**Describe the solution you'd like**
Member specific authentication done inside discord by the bot for OSF Dev team recruits in order to maintain proficiency and authenticity.

**Describe alternatives you've considered**
Verification Bots like captcha.etc

**Additional context**
NA

**Comment by abhigyantrips** [comment]
This is currently blocked by #10 and #17, since it will require member info to be fetched from the database.

**Comment by abhigyantrips** [comment]
Since we're directly making an API request to the database now, there isn't a need to wait for the DB pool or Docker to be implemented.
